### ISSUE TITLE
String values longer than 1024 characters cause database error

### ISSUE THREAD

**Issue by randlet** [qatrackplus/qatrackplus#92]
**[Original report](https://bitbucket.org/tohccmedphys/qatrackplus/issue/92) by Randle Taylor (Bitbucket: [randlet](https://bitbucket.org/randlet), GitHub: [randlet](https://github.com/randlet)).**

----------------------------------------

Needs form validation to prevent these errors.

**Comment by sama2689** [comment]
Hello,
Could you clarify this comment? I can't see the comment as bitbucket access is denied for me. How do we add MaxLengthValidator for a macro? Does this change anything about the macro itself? I have a string composite macro that is a dictionary which I cannot submit as a result because of the 1024 character limit, how would I get around this using the MaxLengthValidator?
